name: Deploy Firestore Rules

on:
  push:
    branches:
      - main
    paths:
      - 'firestore.rules'

jobs:
  deploy_firestore_rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repo
      - run: yarn
        name: Install dependencies
      - run: yarn run firebase deploy --only firestore:rules
        name: Deploy Firestore Security Rules
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
