name: Deploy Firestore Rules

on:
  push:
    branches:
      - main
    paths:
      - 'firestore.rules'

jobs:
  deploy_firestore_rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: firebase deploy --only firestore:rules
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
