name: Deploy Firestore Rules

on:
  push:
     branches:
     - main
     - dev
<<<<<<< HEAD
=======
        # dev is only here temporarily. this needs to go when we release v1
>>>>>>> 99411d4... fix: correct formatting of action triggers
      paths:
        - 'firestore.rules'
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repo
      - run: yarn
        name: Install dependencies
      - run: yarn run firebase deploy --only firestore:rules --project ${{ secrets.FIREBASE_PROJECT_ID }}
        name: Deploy Firestore Security Rules
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
